module.exports = {

  ActionTypes: {
    RECEIVE_RAW_SONGS: 1,

    USER_LOGIN: 20,
    USER_LOGIN_SUCCESS: 21,
    USER_LOGIN_ERROR: 22,

    USER_LOGOUT: 30,
    USER_LOGOUT_SUCCESS: 31,
    USER_LOGOUT_ERROR: 32,

    ADD_SONG: 40,
    ADD_SONG_SUCCESS: 41,
    ADD_SONG_ERROR: 42,

    RATE_QUEUED_SONG: 50,
    RATE_QUEUED_SONG_SUCCESS: 51,
    RATE_QUEUED_SONG_ERROR: 52,
  }
};
